// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pay_client.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ORDER_STATUS int32

const (
	ORDER_STATUS_WAIT       ORDER_STATUS = 0  //待处理
	ORDER_STATUS_PROCESSING ORDER_STATUS = 1  //处理中
	ORDER_STATUS_ABNORMAL   ORDER_STATUS = 2  //异常
	ORDER_STATUS_FAILURE    ORDER_STATUS = 9  //失败
	ORDER_STATUS_SUCCESS    ORDER_STATUS = 10 //成功
)

// Enum value maps for ORDER_STATUS.
var (
	ORDER_STATUS_name = map[int32]string{
		0:  "WAIT",
		1:  "PROCESSING",
		2:  "ABNORMAL",
		9:  "FAILURE",
		10: "SUCCESS",
	}
	ORDER_STATUS_value = map[string]int32{
		"WAIT":       0,
		"PROCESSING": 1,
		"ABNORMAL":   2,
		"FAILURE":    9,
		"SUCCESS":    10,
	}
)

func (x ORDER_STATUS) Enum() *ORDER_STATUS {
	p := new(ORDER_STATUS)
	*p = x
	return p
}

func (x ORDER_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ORDER_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_client_proto_enumTypes[0].Descriptor()
}

func (ORDER_STATUS) Type() protoreflect.EnumType {
	return &file_pay_client_proto_enumTypes[0]
}

func (x ORDER_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ORDER_STATUS.Descriptor instead.
func (ORDER_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{0}
}

type ORDER_TYPE int32

const (
	ORDER_TYPE_ALL     ORDER_TYPE = 0
	ORDER_TYPE_RECEIVE ORDER_TYPE = 1
	ORDER_TYPE_OUT     ORDER_TYPE = 2
	ORDER_TYPE_VIRTUAL ORDER_TYPE = 3
)

// Enum value maps for ORDER_TYPE.
var (
	ORDER_TYPE_name = map[int32]string{
		0: "ALL",
		1: "RECEIVE",
		2: "OUT",
		3: "VIRTUAL",
	}
	ORDER_TYPE_value = map[string]int32{
		"ALL":     0,
		"RECEIVE": 1,
		"OUT":     2,
		"VIRTUAL": 3,
	}
)

func (x ORDER_TYPE) Enum() *ORDER_TYPE {
	p := new(ORDER_TYPE)
	*p = x
	return p
}

func (x ORDER_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ORDER_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_client_proto_enumTypes[1].Descriptor()
}

func (ORDER_TYPE) Type() protoreflect.EnumType {
	return &file_pay_client_proto_enumTypes[1]
}

func (x ORDER_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ORDER_TYPE.Descriptor instead.
func (ORDER_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{1}
}

type PayRpcResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRpcResp) Reset() {
	*x = PayRpcResp{}
	mi := &file_pay_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRpcResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRpcResp) ProtoMessage() {}

func (x *PayRpcResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRpcResp.ProtoReflect.Descriptor instead.
func (*PayRpcResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{0}
}

func (x *PayRpcResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayRpcResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PayRpcResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PayRpcParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRpcParam) Reset() {
	*x = PayRpcParam{}
	mi := &file_pay_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRpcParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRpcParam) ProtoMessage() {}

func (x *PayRpcParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRpcParam.ProtoReflect.Descriptor instead.
func (*PayRpcParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{1}
}

func (x *PayRpcParam) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *PayRpcParam) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 虚拟账户请求参数
type VirtualParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`        //订单号
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`                               //用户ID
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                 //IP地址
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                           //邮箱
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                           //手机号
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`                             //姓名
	Pid           int32                  `protobuf:"varint,10,opt,name=pid,proto3" json:"pid,omitempty"`                             //通道ID
	IdNum         string                 `protobuf:"bytes,11,opt,name=id_num,json=idNum,proto3" json:"id_num,omitempty"`             //身份证号
	NotifyUrl     string                 `protobuf:"bytes,12,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"` //回调地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualParam) Reset() {
	*x = VirtualParam{}
	mi := &file_pay_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualParam) ProtoMessage() {}

func (x *VirtualParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualParam.ProtoReflect.Descriptor instead.
func (*VirtualParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{2}
}

func (x *VirtualParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *VirtualParam) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VirtualParam) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VirtualParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VirtualParam) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *VirtualParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualParam) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *VirtualParam) GetIdNum() string {
	if x != nil {
		return x.IdNum
	}
	return ""
}

func (x *VirtualParam) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

// 虚拟账户响应结果
type VirtualResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`             //订单号
	MerchantNo    string                 `protobuf:"bytes,2,opt,name=merchant_no,json=merchantNo,proto3" json:"merchant_no,omitempty"`    //商户订单号
	AccountName   string                 `protobuf:"bytes,3,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"` //账户名称
	AccountNo     string                 `protobuf:"bytes,4,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`       //账户号
	PayUrl        string                 `protobuf:"bytes,5,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`                //付款页面地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualResp) Reset() {
	*x = VirtualResp{}
	mi := &file_pay_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualResp) ProtoMessage() {}

func (x *VirtualResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualResp.ProtoReflect.Descriptor instead.
func (*VirtualResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *VirtualResp) GetMerchantNo() string {
	if x != nil {
		return x.MerchantNo
	}
	return ""
}

func (x *VirtualResp) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *VirtualResp) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *VirtualResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

// 收款单请求参数
type ReceiveParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`        //订单号
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                        //订单金额（分）
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`                               //用户ID
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                 //IP地址
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                           //邮箱
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                           //手机号
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`                             //姓名
	Mode          string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`                             //1支付宝，2微信，3银行卡
	Pid           int32                  `protobuf:"varint,9,opt,name=pid,proto3" json:"pid,omitempty"`                              //通道ID
	IdNum         string                 `protobuf:"bytes,10,opt,name=id_num,json=idNum,proto3" json:"id_num,omitempty"`             //身份证号
	NotifyUrl     string                 `protobuf:"bytes,11,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"` //回调地址
	ReturnUrl     string                 `protobuf:"bytes,12,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"` //跳转地址
	Subject       string                 `protobuf:"bytes,14,opt,name=subject,proto3" json:"subject,omitempty"`                      //支付备注
	Body          string                 `protobuf:"bytes,15,opt,name=body,proto3" json:"body,omitempty"`                            //支付描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveParam) Reset() {
	*x = ReceiveParam{}
	mi := &file_pay_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveParam) ProtoMessage() {}

func (x *ReceiveParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveParam.ProtoReflect.Descriptor instead.
func (*ReceiveParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ReceiveParam) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReceiveParam) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ReceiveParam) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ReceiveParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReceiveParam) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ReceiveParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReceiveParam) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ReceiveParam) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ReceiveParam) GetIdNum() string {
	if x != nil {
		return x.IdNum
	}
	return ""
}

func (x *ReceiveParam) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *ReceiveParam) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *ReceiveParam) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ReceiveParam) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// 收款单响应结果
type ReceiveResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`          //订单号
	MerchantNo    string                 `protobuf:"bytes,2,opt,name=merchant_no,json=merchantNo,proto3" json:"merchant_no,omitempty"` //商户订单号
	PayUrl        string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`             //付款页面地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveResp) Reset() {
	*x = ReceiveResp{}
	mi := &file_pay_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResp) ProtoMessage() {}

func (x *ReceiveResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResp.ProtoReflect.Descriptor instead.
func (*ReceiveResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *ReceiveResp) GetMerchantNo() string {
	if x != nil {
		return x.MerchantNo
	}
	return ""
}

func (x *ReceiveResp) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

// 付款单请求参数
type OutParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`     //订单号
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                     //金额
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`                            //用户ID
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                              //IP地址
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                        //邮箱
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`                        //手机号
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`                          //姓名
	IdNum         string                 `protobuf:"bytes,8,opt,name=id_num,json=idNum,proto3" json:"id_num,omitempty"`           //身份证件号码
	Pid           int32                  `protobuf:"varint,9,opt,name=pid,proto3" json:"pid,omitempty"`                           //通道ID
	BankNo        string                 `protobuf:"bytes,10,opt,name=bank_no,json=bankNo,proto3" json:"bank_no,omitempty"`       //银行账号
	BankCode      string                 `protobuf:"bytes,11,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"` //银行编码
	BankName      string                 `protobuf:"bytes,12,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	Mode          string                 `protobuf:"bytes,13,opt,name=mode,proto3" json:"mode,omitempty"`                            //1支付宝，2微信，3银行卡
	NotifyUrl     string                 `protobuf:"bytes,14,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"` //回调地址
	Subject       string                 `protobuf:"bytes,15,opt,name=subject,proto3" json:"subject,omitempty"`                      //支付备注
	Body          string                 `protobuf:"bytes,16,opt,name=body,proto3" json:"body,omitempty"`                            //支付描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutParam) Reset() {
	*x = OutParam{}
	mi := &file_pay_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutParam) ProtoMessage() {}

func (x *OutParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutParam.ProtoReflect.Descriptor instead.
func (*OutParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{6}
}

func (x *OutParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OutParam) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OutParam) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *OutParam) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OutParam) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OutParam) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OutParam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OutParam) GetIdNum() string {
	if x != nil {
		return x.IdNum
	}
	return ""
}

func (x *OutParam) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *OutParam) GetBankNo() string {
	if x != nil {
		return x.BankNo
	}
	return ""
}

func (x *OutParam) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *OutParam) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *OutParam) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *OutParam) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *OutParam) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *OutParam) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

// 付款单响应结果
type OutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`          //订单号
	MerchantNo    string                 `protobuf:"bytes,2,opt,name=merchant_no,json=merchantNo,proto3" json:"merchant_no,omitempty"` //商户订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutResp) Reset() {
	*x = OutResp{}
	mi := &file_pay_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutResp) ProtoMessage() {}

func (x *OutResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutResp.ProtoReflect.Descriptor instead.
func (*OutResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{7}
}

func (x *OutResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OutResp) GetMerchantNo() string {
	if x != nil {
		return x.MerchantNo
	}
	return ""
}

// 订单查询参数
type OrderQueryParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`          //订单号
	MerchantNo    string                 `protobuf:"bytes,2,opt,name=merchant_no,json=merchantNo,proto3" json:"merchant_no,omitempty"` //商户订单号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQueryParam) Reset() {
	*x = OrderQueryParam{}
	mi := &file_pay_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQueryParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQueryParam) ProtoMessage() {}

func (x *OrderQueryParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQueryParam.ProtoReflect.Descriptor instead.
func (*OrderQueryParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{8}
}

func (x *OrderQueryParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderQueryParam) GetMerchantNo() string {
	if x != nil {
		return x.MerchantNo
	}
	return ""
}

// 订单查询响应结果
type OrderQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`           //订单号
	MerchantNo    string                 `protobuf:"bytes,2,opt,name=merchant_no,json=merchantNo,proto3" json:"merchant_no,omitempty"`  //商户订单号
	PayNo         string                 `protobuf:"bytes,3,opt,name=pay_no,json=payNo,proto3" json:"pay_no,omitempty"`                 //支付订单号
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`                           //金额
	Fee           int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`                                 //手续费
	Status        ORDER_STATUS           `protobuf:"varint,6,opt,name=status,proto3,enum=pb.ORDER_STATUS" json:"status,omitempty"`      //状态
	UpdateTime    int64                  `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` //更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderQueryResp) Reset() {
	*x = OrderQueryResp{}
	mi := &file_pay_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderQueryResp) ProtoMessage() {}

func (x *OrderQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderQueryResp.ProtoReflect.Descriptor instead.
func (*OrderQueryResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{9}
}

func (x *OrderQueryResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderQueryResp) GetMerchantNo() string {
	if x != nil {
		return x.MerchantNo
	}
	return ""
}

func (x *OrderQueryResp) GetPayNo() string {
	if x != nil {
		return x.PayNo
	}
	return ""
}

func (x *OrderQueryResp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderQueryResp) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *OrderQueryResp) GetStatus() ORDER_STATUS {
	if x != nil {
		return x.Status
	}
	return ORDER_STATUS_WAIT
}

func (x *OrderQueryResp) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CallbackParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`           //订单号
	MerchantNo    string                 `protobuf:"bytes,2,opt,name=merchant_no,json=merchantNo,proto3" json:"merchant_no,omitempty"`  //商户订单号
	RealAmount    int64                  `protobuf:"varint,4,opt,name=real_amount,json=realAmount,proto3" json:"real_amount,omitempty"` //实际金额
	Fee           int64                  `protobuf:"varint,5,opt,name=fee,proto3" json:"fee,omitempty"`                                 //平台手续费
	Status        ORDER_STATUS           `protobuf:"varint,6,opt,name=status,proto3,enum=pb.ORDER_STATUS" json:"status,omitempty"`      //订单状态
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`                            //备注
	FinishTime    int64                  `protobuf:"varint,8,opt,name=finish_time,json=finishTime,proto3" json:"finish_time,omitempty"` //结束时间
	Uid           string                 `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`                                  //商户用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackParam) Reset() {
	*x = CallbackParam{}
	mi := &file_pay_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackParam) ProtoMessage() {}

func (x *CallbackParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackParam.ProtoReflect.Descriptor instead.
func (*CallbackParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{10}
}

func (x *CallbackParam) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CallbackParam) GetMerchantNo() string {
	if x != nil {
		return x.MerchantNo
	}
	return ""
}

func (x *CallbackParam) GetRealAmount() int64 {
	if x != nil {
		return x.RealAmount
	}
	return 0
}

func (x *CallbackParam) GetFee() int64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *CallbackParam) GetStatus() ORDER_STATUS {
	if x != nil {
		return x.Status
	}
	return ORDER_STATUS_WAIT
}

func (x *CallbackParam) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CallbackParam) GetFinishTime() int64 {
	if x != nil {
		return x.FinishTime
	}
	return 0
}

func (x *CallbackParam) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ChannelQueryParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderType     ORDER_TYPE             `protobuf:"varint,1,opt,name=order_type,json=orderType,proto3,enum=pb.ORDER_TYPE" json:"order_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelQueryParam) Reset() {
	*x = ChannelQueryParam{}
	mi := &file_pay_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelQueryParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelQueryParam) ProtoMessage() {}

func (x *ChannelQueryParam) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelQueryParam.ProtoReflect.Descriptor instead.
func (*ChannelQueryParam) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{11}
}

func (x *ChannelQueryParam) GetOrderType() ORDER_TYPE {
	if x != nil {
		return x.OrderType
	}
	return ORDER_TYPE_ALL
}

// 支付通道查询响应结果
type ChannelQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int64                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Pid           int32                  `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	SingleMin     int64                  `protobuf:"varint,6,opt,name=single_min,json=singleMin,proto3" json:"single_min,omitempty"`
	SingleMax     int64                  `protobuf:"varint,7,opt,name=single_max,json=singleMax,proto3" json:"single_max,omitempty"`
	DayMax        int64                  `protobuf:"varint,8,opt,name=day_max,json=dayMax,proto3" json:"day_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelQueryResp) Reset() {
	*x = ChannelQueryResp{}
	mi := &file_pay_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelQueryResp) ProtoMessage() {}

func (x *ChannelQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelQueryResp.ProtoReflect.Descriptor instead.
func (*ChannelQueryResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{12}
}

func (x *ChannelQueryResp) GetChannel() int64 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *ChannelQueryResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelQueryResp) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ChannelQueryResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ChannelQueryResp) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ChannelQueryResp) GetSingleMin() int64 {
	if x != nil {
		return x.SingleMin
	}
	return 0
}

func (x *ChannelQueryResp) GetSingleMax() int64 {
	if x != nil {
		return x.SingleMax
	}
	return 0
}

func (x *ChannelQueryResp) GetDayMax() int64 {
	if x != nil {
		return x.DayMax
	}
	return 0
}

// 商户余额查询响应结果
type MerchantBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`              //账户名称
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`           //总余额
	Available     int64                  `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`   //可用余额
	Settlement    int64                  `protobuf:"varint,4,opt,name=settlement,proto3" json:"settlement,omitempty"` //待结算余额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantBalanceResp) Reset() {
	*x = MerchantBalanceResp{}
	mi := &file_pay_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantBalanceResp) ProtoMessage() {}

func (x *MerchantBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantBalanceResp.ProtoReflect.Descriptor instead.
func (*MerchantBalanceResp) Descriptor() ([]byte, []int) {
	return file_pay_client_proto_rawDescGZIP(), []int{13}
}

func (x *MerchantBalanceResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantBalanceResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MerchantBalanceResp) GetAvailable() int64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MerchantBalanceResp) GetSettlement() int64 {
	if x != nil {
		return x.Settlement
	}
	return 0
}

var File_pay_client_proto protoreflect.FileDescriptor

const file_pay_client_proto_rawDesc = "" +
	"\n" +
	"\x10pay_client.proto\x12\x02pb\"P\n" +
	"\fpay_rpc_resp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"<\n" +
	"\rpay_rpc_param\x12\x17\n" +
	"\aapp_key\x18\x01 \x01(\tR\x06appKey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\xd4\x01\n" +
	"\rvirtual_param\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x10\n" +
	"\x03pid\x18\n" +
	" \x01(\x05R\x03pid\x12\x15\n" +
	"\x06id_num\x18\v \x01(\tR\x05idNum\x12\x1d\n" +
	"\n" +
	"notify_url\x18\f \x01(\tR\tnotifyUrl\"\xa5\x01\n" +
	"\fvirtual_resp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_no\x18\x02 \x01(\tR\n" +
	"merchantNo\x12!\n" +
	"\faccount_name\x18\x03 \x01(\tR\vaccountName\x12\x1d\n" +
	"\n" +
	"account_no\x18\x04 \x01(\tR\taccountNo\x12\x17\n" +
	"\apay_url\x18\x05 \x01(\tR\x06payUrl\"\xcd\x02\n" +
	"\rreceive_param\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12\x10\n" +
	"\x03pid\x18\t \x01(\x05R\x03pid\x12\x15\n" +
	"\x06id_num\x18\n" +
	" \x01(\tR\x05idNum\x12\x1d\n" +
	"\n" +
	"notify_url\x18\v \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\f \x01(\tR\treturnUrl\x12\x18\n" +
	"\asubject\x18\x0e \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x0f \x01(\tR\x04body\"c\n" +
	"\freceive_resp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_no\x18\x02 \x01(\tR\n" +
	"merchantNo\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl\"\xfd\x02\n" +
	"\tout_param\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12\x15\n" +
	"\x06id_num\x18\b \x01(\tR\x05idNum\x12\x10\n" +
	"\x03pid\x18\t \x01(\x05R\x03pid\x12\x17\n" +
	"\abank_no\x18\n" +
	" \x01(\tR\x06bankNo\x12\x1b\n" +
	"\tbank_code\x18\v \x01(\tR\bbankCode\x12\x1b\n" +
	"\tbank_name\x18\f \x01(\tR\bbankName\x12\x12\n" +
	"\x04mode\x18\r \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x0e \x01(\tR\tnotifyUrl\x12\x18\n" +
	"\asubject\x18\x0f \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x10 \x01(\tR\x04body\"F\n" +
	"\bout_resp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_no\x18\x02 \x01(\tR\n" +
	"merchantNo\"O\n" +
	"\x11order_query_param\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_no\x18\x02 \x01(\tR\n" +
	"merchantNo\"\xda\x01\n" +
	"\x10order_query_resp\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_no\x18\x02 \x01(\tR\n" +
	"merchantNo\x12\x15\n" +
	"\x06pay_no\x18\x03 \x01(\tR\x05payNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.pb.ORDER_STATUSR\x06status\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\x03R\n" +
	"updateTime\"\xf4\x01\n" +
	"\x0ecallback_param\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vmerchant_no\x18\x02 \x01(\tR\n" +
	"merchantNo\x12\x1f\n" +
	"\vreal_amount\x18\x04 \x01(\x03R\n" +
	"realAmount\x12\x10\n" +
	"\x03fee\x18\x05 \x01(\x03R\x03fee\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.pb.ORDER_STATUSR\x06status\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12\x1f\n" +
	"\vfinish_time\x18\b \x01(\x03R\n" +
	"finishTime\x12\x10\n" +
	"\x03uid\x18\t \x01(\tR\x03uid\"D\n" +
	"\x13channel_query_param\x12-\n" +
	"\n" +
	"order_type\x18\x01 \x01(\x0e2\x0e.pb.ORDER_TYPER\torderType\"\xd7\x01\n" +
	"\x12channel_query_resp\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x03R\achannel\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x10\n" +
	"\x03pid\x18\x05 \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"single_min\x18\x06 \x01(\x03R\tsingleMin\x12\x1d\n" +
	"\n" +
	"single_max\x18\a \x01(\x03R\tsingleMax\x12\x17\n" +
	"\aday_max\x18\b \x01(\x03R\x06dayMax\"\x7f\n" +
	"\x15merchant_balance_resp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\x03R\tavailable\x12\x1e\n" +
	"\n" +
	"settlement\x18\x04 \x01(\x03R\n" +
	"settlement*P\n" +
	"\fORDER_STATUS\x12\b\n" +
	"\x04WAIT\x10\x00\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x01\x12\f\n" +
	"\bABNORMAL\x10\x02\x12\v\n" +
	"\aFAILURE\x10\t\x12\v\n" +
	"\aSUCCESS\x10\n" +
	"*8\n" +
	"\n" +
	"ORDER_TYPE\x12\a\n" +
	"\x03ALL\x10\x00\x12\v\n" +
	"\aRECEIVE\x10\x01\x12\a\n" +
	"\x03OUT\x10\x02\x12\v\n" +
	"\aVIRTUAL\x10\x032\xf8\x02\n" +
	"\vpay_service\x126\n" +
	"\x0fvirtual_account\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_resp\x12.\n" +
	"\areceive\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_resp\x124\n" +
	"\rreceive_query\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_resp\x12*\n" +
	"\x03out\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_resp\x120\n" +
	"\tout_query\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_resp\x124\n" +
	"\rchannel_query\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_resp\x127\n" +
	"\x10merchant_balance\x12\x11.pb.pay_rpc_param\x1a\x10.pb.pay_rpc_respB\aZ\x05./;pbb\x06proto3"

var (
	file_pay_client_proto_rawDescOnce sync.Once
	file_pay_client_proto_rawDescData []byte
)

func file_pay_client_proto_rawDescGZIP() []byte {
	file_pay_client_proto_rawDescOnce.Do(func() {
		file_pay_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pay_client_proto_rawDesc), len(file_pay_client_proto_rawDesc)))
	})
	return file_pay_client_proto_rawDescData
}

var file_pay_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pay_client_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pay_client_proto_goTypes = []any{
	(ORDER_STATUS)(0),           // 0: pb.ORDER_STATUS
	(ORDER_TYPE)(0),             // 1: pb.ORDER_TYPE
	(*PayRpcResp)(nil),          // 2: pb.pay_rpc_resp
	(*PayRpcParam)(nil),         // 3: pb.pay_rpc_param
	(*VirtualParam)(nil),        // 4: pb.virtual_param
	(*VirtualResp)(nil),         // 5: pb.virtual_resp
	(*ReceiveParam)(nil),        // 6: pb.receive_param
	(*ReceiveResp)(nil),         // 7: pb.receive_resp
	(*OutParam)(nil),            // 8: pb.out_param
	(*OutResp)(nil),             // 9: pb.out_resp
	(*OrderQueryParam)(nil),     // 10: pb.order_query_param
	(*OrderQueryResp)(nil),      // 11: pb.order_query_resp
	(*CallbackParam)(nil),       // 12: pb.callback_param
	(*ChannelQueryParam)(nil),   // 13: pb.channel_query_param
	(*ChannelQueryResp)(nil),    // 14: pb.channel_query_resp
	(*MerchantBalanceResp)(nil), // 15: pb.merchant_balance_resp
}
var file_pay_client_proto_depIdxs = []int32{
	0,  // 0: pb.order_query_resp.status:type_name -> pb.ORDER_STATUS
	0,  // 1: pb.callback_param.status:type_name -> pb.ORDER_STATUS
	1,  // 2: pb.channel_query_param.order_type:type_name -> pb.ORDER_TYPE
	3,  // 3: pb.pay_service.virtual_account:input_type -> pb.pay_rpc_param
	3,  // 4: pb.pay_service.receive:input_type -> pb.pay_rpc_param
	3,  // 5: pb.pay_service.receive_query:input_type -> pb.pay_rpc_param
	3,  // 6: pb.pay_service.out:input_type -> pb.pay_rpc_param
	3,  // 7: pb.pay_service.out_query:input_type -> pb.pay_rpc_param
	3,  // 8: pb.pay_service.channel_query:input_type -> pb.pay_rpc_param
	3,  // 9: pb.pay_service.merchant_balance:input_type -> pb.pay_rpc_param
	2,  // 10: pb.pay_service.virtual_account:output_type -> pb.pay_rpc_resp
	2,  // 11: pb.pay_service.receive:output_type -> pb.pay_rpc_resp
	2,  // 12: pb.pay_service.receive_query:output_type -> pb.pay_rpc_resp
	2,  // 13: pb.pay_service.out:output_type -> pb.pay_rpc_resp
	2,  // 14: pb.pay_service.out_query:output_type -> pb.pay_rpc_resp
	2,  // 15: pb.pay_service.channel_query:output_type -> pb.pay_rpc_resp
	2,  // 16: pb.pay_service.merchant_balance:output_type -> pb.pay_rpc_resp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_pay_client_proto_init() }
func file_pay_client_proto_init() {
	if File_pay_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pay_client_proto_rawDesc), len(file_pay_client_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_client_proto_goTypes,
		DependencyIndexes: file_pay_client_proto_depIdxs,
		EnumInfos:         file_pay_client_proto_enumTypes,
		MessageInfos:      file_pay_client_proto_msgTypes,
	}.Build()
	File_pay_client_proto = out.File
	file_pay_client_proto_goTypes = nil
	file_pay_client_proto_depIdxs = nil
}
